-- New table:sysvar55
-- Create table entry
DROP TABLE IF EXISTS sysvar55;
CREATE TABLE sysvar55 (
    id int unsigned auto_increment NOT NULL,
    system_variable_name varchar(255) NOT NULL,
    cmd_line varchar(255) DEFAULT NULL,
    option_file varchar(50) DEFAULT NULL,
    system_var varchar(50) DEFAULT NULL,
    var_scope varchar(50) DEFAULT NULL,
    dynamic varchar(50) DEFAULT NULL,
    data_type varchar(50) DEFAULT NULL,
    PRIMARY KEY (system_variable_name),
    UNIQUE KEY ( id )
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- Insert rows
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('audit_log_buffer_size','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('audit_log_file','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('audit_log_flush',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('audit_log_format','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('audit_log_policy','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('audit_log_rotate_on_size','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('audit_log_strategy','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('auto_increment_increment',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('auto_increment_offset',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('autocommit','Yes','Yes','Yes','Varies','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('automatic_sp_privileges',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('back_log',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('basedir','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('big-tables','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('big_tables',' ',' ','Yes','Varies','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('binlog_cache_size','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('binlog_direct_non_transactional_updates','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('binlog-format','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('binlog_format',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('binlog_stmt_cache_size','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('bulk_insert_buffer_size','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('character_set_client',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('character_set_connection',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('[a]',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('character-set-filesystem','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('character_set_filesystem',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('character_set_results',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('character-set-server','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('character_set_server',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('character_set_system',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('character-sets-dir','Yes','Yes',' ',' ','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('character_sets_dir',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('collation_connection',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('[b]',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('collation-server','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('collation_server',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('completion_type','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('concurrent_insert','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('connect_timeout','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('datadir','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('date_format',' ',' ','Yes','Varies','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('datetime_format',' ',' ','Yes','Varies','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('debug','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('debug_sync',' ',' ','Yes','Varies','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('default-storage-engine','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('default_storage_engine',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('default_week_format','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('delay-key-write','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('delay_key_write',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('delayed_insert_limit','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('delayed_insert_timeout','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('delayed_queue_size','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('div_precision_increment','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('engine-condition-pushdown','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('engine_condition_pushdown',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('error_count',' ',' ','Yes','Session','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('event-scheduler','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('event_scheduler',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('expire_logs_days','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('external_user',' ',' ','Yes','Session','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('flush','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('flush_time','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('foreign_key_checks',' ',' ','Yes','Varies','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ft_boolean_syntax','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ft_max_word_len','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ft_min_word_len','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ft_query_expansion_limit','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ft_stopword_file','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('general-log','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('general_log',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('general_log_file','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('group_concat_max_len','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_compress',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_crypt',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_csv',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_dynamic_loading',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_geometry',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_innodb',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_ndbcluster',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_openssl',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_partitioning',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_profiling',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_query_cache',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_rtree_keys',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_ssl',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_symlink',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('hostname',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('identity',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ignore-builtin-innodb','Yes','Yes',' ',' ','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ignore_builtin_innodb',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('init_connect','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('init-file','Yes','Yes',' ',' ','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('init_file',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('init_slave','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_adaptive_flushing','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_adaptive_hash_index','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_additional_mem_pool_size','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_autoextend_increment','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_autoinc_lock_mode','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_buffer_pool_instances','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_buffer_pool_size','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_change_buffering','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_change_buffering_debug','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_checksums','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_commit_concurrency','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_concurrency_tickets','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_data_file_path','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_data_home_dir','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_doublewrite','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_fast_shutdown','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_file_format','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_file_format_check','Yes','Yes','Yes','Global','Varies');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_file_format_max','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_file_per_table','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_flush_log_at_trx_commit','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_flush_method','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_force_load_corrupted','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_force_recovery','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_io_capacity','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_large_prefix','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_limit_optimistic_insert_debug','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_lock_wait_timeout','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_locks_unsafe_for_binlog','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_log_buffer_size','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_log_file_size','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_log_files_in_group','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_log_group_home_dir','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_max_dirty_pages_pct','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_max_purge_lag','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_mirrored_log_groups','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_old_blocks_pct','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_old_blocks_time','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_open_files','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_print_all_deadlocks','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_purge_batch_size','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_purge_threads','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_random_read_ahead','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_read_ahead_threshold','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_read_io_threads','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_replication_delay','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_rollback_on_timeout','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_rollback_segments','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_spin_wait_delay','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_stats_method','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_stats_on_metadata','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_stats_sample_pages','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_strict_mode','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_support_xa','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_sync_spin_loops','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_table_locks','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_thread_concurrency','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_thread_sleep_delay','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_trx_purge_view_update_only_debug','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_trx_rseg_n_slots_debug','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_use_native_aio','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_use_sys_malloc','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_version',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_write_io_threads','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('insert_id',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('interactive_timeout','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('join_buffer_size','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('keep_files_on_create','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('key_buffer_size','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('key_cache_age_threshold','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('key_cache_block_size','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('key_cache_division_limit','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('language','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('large_files_support',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('large_page_size',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('large-pages','Yes','Yes',' ',' ','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('large_pages',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('last_insert_id',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('lc-messages','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('lc_messages',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('lc-messages-dir','Yes','Yes',' ',' ','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('lc_messages_dir',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('lc_time_names',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('license',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('local_infile',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('lock_wait_timeout','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('locked_in_memory',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log_bin',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log-bin','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log-bin-trust-function-creators','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log_bin_trust_function_creators',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log-bin-trust-routine-creators','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log_bin_trust_routine_creators',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log_bin_use_v1_row_events','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log-bin-use-v1-row-events','Yes','Yes',' ',' ','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log-error','Yes','Yes',' ',' ','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log_error',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log-output','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log_output',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log-queries-not-using-indexes','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log_queries_not_using_indexes',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log-slave-updates','Yes','Yes',' ',' ','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log_slave_updates','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log-slow-queries','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log_slow_queries',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log-warnings','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log_warnings',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('long_query_time','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('low-priority-updates','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('low_priority_updates',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('lower_case_file_system',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('lower_case_table_names','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_allowed_packet','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_binlog_cache_size','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_binlog_size','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_binlog_stmt_cache_size','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_connect_errors','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_connections','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_delayed_threads','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_error_count','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_heap_table_size','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_insert_delayed_threads',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_join_size','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_length_for_sort_data','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_long_data_size','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_prepared_stmt_count','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_relay_log_size','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_seeks_for_key','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_sort_length','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_sp_recursion_depth','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_tmp_tables',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_user_connections','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_write_lock_count','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('metadata_locks_cache_size',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('min-examined-row-limit','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('multi_range_count','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('myisam_data_pointer_size','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('myisam_max_sort_file_size','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('myisam_mmap_size','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('myisam_recover_options',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('myisam_repair_threads','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('myisam_sort_buffer_size','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('myisam_stats_method','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('myisam_use_mmap','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('named_pipe',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_autoincrement_prefetch_sz','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb-batch-size','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb-blob-read-batch-bytes','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb-blob-write-batch-bytes','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_cache_check_time','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb-cluster-connection-pool','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb-deferred-constraints','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_deferred_constraints','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_distribution','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb-distribution','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_eventbuffer_max_alloc','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_extra_logging','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_force_send','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_index_stat_cache_entries','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_index_stat_enable','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_index_stat_option','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_index_stat_update_freq','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_join_pushdown',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb-log-apply-status','Yes','Yes',' ',' ','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_log_apply_status','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_log_bin','Yes',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_log_binlog_index','Yes',' ','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_log_empty_epochs','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb-log-empty-epochs','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb-log-orig','Yes','Yes',' ',' ','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_log_orig','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb-log-transaction-id','Yes','Yes',' ',' ','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_log_transaction_id',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb-log-update-as-write','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_log_updated_only','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_optimization_delay',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_optimized_node_selection','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_table_no_logging',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_table_temporary',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_use_copying_alter_table',' ',' ','Yes','Both','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_use_exact_count',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_use_transactions','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_version',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_version_string',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb-wait-connected','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb-wait-setup','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndbinfo_database',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndbinfo_max_bytes','Yes',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndbinfo_max_rows','Yes',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndbinfo_offline',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndbinfo_show_hidden','Yes',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndbinfo_table_prefix','Yes',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndbinfo_version',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('net_buffer_length','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('net_read_timeout','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('net_retry_count','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('net_write_timeout','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('new','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('old','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('old-alter-table','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('old_alter_table',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('old_passwords',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('open-files-limit','Yes','Yes',' ',' ','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('open_files_limit',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('optimizer_prune_level','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('optimizer_search_depth','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('optimizer_switch','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('performance_schema','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('performance_schema_events_waits_history_long_size','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('performance_schema_events_waits_history_size','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('performance_schema_max_cond_classes','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('performance_schema_max_cond_instances','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('performance_schema_max_file_classes','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('performance_schema_max_file_handles','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('performance_schema_max_file_instances','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('performance_schema_max_mutex_classes','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('performance_schema_max_mutex_instances','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('performance_schema_max_rwlock_classes','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('performance_schema_max_rwlock_instances','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('performance_schema_max_table_handles','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('performance_schema_max_table_instances','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('performance_schema_max_thread_classes','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('performance_schema_max_thread_instances','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('pid-file','Yes','Yes',' ',' ','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('pid_file',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('plugin_dir','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('port','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('preload_buffer_size','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('profiling',' ',' ','Yes','Varies','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('profiling_history_size','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('protocol_version',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('proxy_user',' ',' ','Yes','Session','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('pseudo_slave_mode',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('pseudo_thread_id',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('query_alloc_block_size','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('query_cache_limit','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('query_cache_min_res_unit','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('query_cache_size','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('query_cache_type','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('query_cache_wlock_invalidate','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('query_prealloc_size','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('rand_seed1',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('rand_seed2',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('range_alloc_block_size','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('read_buffer_size','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('read_only','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('read_rnd_buffer_size','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('relay-log','Yes','Yes',' ',' ','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('relay_log',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('relay-log-index','Yes','Yes',' ',' ','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('relay_log_index','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('relay_log_info_file','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('relay_log_purge','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('relay_log_recovery','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('relay_log_space_limit','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('report-host','Yes','Yes',' ',' ','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('report_host',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('report-password','Yes','Yes',' ',' ','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('report_password',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('report-port','Yes','Yes',' ',' ','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('report_port',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('report-user','Yes','Yes',' ',' ','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('report_user',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('rpl_recovery_rank',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('rpl_semi_sync_master_enabled',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('rpl_semi_sync_master_timeout',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('rpl_semi_sync_master_trace_level',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('rpl_semi_sync_master_wait_no_slave',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('rpl_semi_sync_slave_enabled',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('rpl_semi_sync_slave_trace_level',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('secure-auth','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('secure_auth',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('secure-file-priv','Yes','Yes',' ',' ','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('secure_file_priv',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('server-id','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('server_id',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('server_id_bits','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('server-id-bits','Yes','Yes',' ',' ','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('shared_memory','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('shared_memory_base_name','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('skip_external_locking','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('skip-name-resolve','Yes','Yes',' ',' ','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('skip_name_resolve',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('skip-networking','Yes','Yes',' ',' ','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('skip_networking',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('skip-show-database','Yes','Yes',' ',' ','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('skip_show_database',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('slave_allow_batching','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('slave_compressed_protocol','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('slave_exec_mode','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('slave-load-tmpdir','Yes','Yes',' ',' ','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('slave_load_tmpdir',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('slave_max_allowed_packet',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('slave-net-timeout','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('slave_net_timeout',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('slave-skip-errors','Yes','Yes',' ',' ','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('slave_skip_errors',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('slave_transaction_retries','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('slave_type_conversions','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('slow_launch_time','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('slow-query-log','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('slow_query_log',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('slow_query_log_file','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('socket','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sort_buffer_size','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sql_auto_is_null',' ',' ','Yes','Varies','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sql_big_selects',' ',' ','Yes','Varies','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sql_big_tables',' ',' ','Yes','Varies','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sql_buffer_result',' ',' ','Yes','Varies','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sql_log_bin',' ',' ','Yes','Varies','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sql_log_off',' ',' ','Yes','Varies','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sql_log_update',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sql_low_priority_updates',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sql_max_join_size',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sql-mode','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sql_mode',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sql_notes',' ',' ','Yes','Varies','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sql_quote_show_create',' ',' ','Yes','Varies','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sql_safe_updates',' ',' ','Yes','Varies','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sql_select_limit',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sql_slave_skip_counter',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sql_warnings',' ',' ','Yes','Varies','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ssl-ca','Yes','Yes',' ',' ','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ssl_ca',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ssl-capath','Yes','Yes',' ',' ','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ssl_capath',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ssl-cert','Yes','Yes',' ',' ','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ssl_cert',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ssl-cipher','Yes','Yes',' ',' ','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ssl_cipher',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ssl-key','Yes','Yes',' ',' ','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ssl_key',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('storage_engine',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('stored_program_cache','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sync_binlog','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sync_frm','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sync_master_info','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sync_relay_log','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sync_relay_log_info','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('system_time_zone',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('table_definition_cache',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('table_lock_wait_timeout','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('table_open_cache',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('table_type',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('thread_cache_size','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('thread_concurrency','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('thread_handling','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('thread_pool_algorithm','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('thread_pool_high_priority_connection','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('thread_pool_max_unused_threads','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('thread_pool_prio_kickup_timer','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('thread_pool_size','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('thread_pool_stall_limit','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('thread_stack','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('time_format',' ',' ','Yes','Varies','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('time_zone',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('timed_mutexes','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('timestamp',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('tmp_table_size','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('tmpdir','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('transaction_alloc_block_size','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('transaction_allow_batching',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('transaction_prealloc_size','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('tx_isolation',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('unique_checks',' ',' ','Yes','Varies','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('updatable_views_with_limit','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('version',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('version_comment',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('version_compile_machine',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('version_compile_os',' ',' ','Yes','Global','No');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('wait_timeout','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar55 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('warning_count',' ',' ','Yes','Session','No');
