-- New table:sysvar50
-- Create table entry
DROP TABLE IF EXISTS sysvar50;
CREATE TABLE sysvar50 (
    system_variable_name varchar(255) NOT NULL,
    cmd_line varchar(255) DEFAULT NULL,
    option_file varchar(50) DEFAULT NULL,
    system_var varchar(50) DEFAULT NULL,
    var_scope varchar(50) DEFAULT NULL,
    dynamic varchar(50) DEFAULT NULL,
    data_type varchar(50) DEFAULT NULL,
    PRIMARY KEY (system_variable_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
-- Insert rows
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('auto_increment_increment',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('auto_increment_offset',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('autocommit',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('automatic_sp_privileges',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('back_log',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('basedir','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('bdb_cache_size',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('bdb-home','Yes','Yes',' ',' ','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('bdb_home',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('bdb-lock-detect','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('bdb_log_buffer_size',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('bdb-logdir','Yes','Yes',' ',' ','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('bdb_logdir',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('bdb_max_lock',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('bdb-shared-data','Yes','Yes',' ',' ','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('bdb_shared_data',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('bdb-tmpdir','Yes','Yes',' ',' ','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('bdb_tmpdir',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('big-tables','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('big_tables',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('binlog_cache_size','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('bulk_insert_buffer_size','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('character_set_client',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('character_set_connection',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('[a]',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('character-set-filesystem','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('character_set_filesystem',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('character_set_results',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('character-set-server','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('character_set_server',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('character_set_system',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('character-sets-dir','Yes','Yes',' ',' ','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('character_sets_dir',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('collation_connection',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('[b]',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('collation-server','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('collation_server',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('completion_type','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('concurrent_insert','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('connect_timeout','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('datadir','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('date_format',' ',' ','Yes','Both','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('datetime_format',' ',' ','Yes','Both','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('debug','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('default-storage-engine','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('default_week_format','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('delay-key-write','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('delay_key_write',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('delayed_insert_limit','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('delayed_insert_timeout','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('delayed_queue_size','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('div_precision_increment','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('engine-condition-pushdown','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('engine_condition_pushdown',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('error_count',' ',' ','Yes','Session','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('expire_logs_days','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('flush','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('flush_time','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('foreign_key_checks',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ft_boolean_syntax','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ft_max_word_len','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ft_min_word_len','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ft_query_expansion_limit','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ft_stopword_file','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('group_concat_max_len','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_archive',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_bdb',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_blackhole_engine',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_community_features',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_compress',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_crypt',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_csv',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_example_engine',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_federated_engine',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_geometry',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_innodb',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_isam',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_merge_engine',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_ndbcluster',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_openssl',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_profiling',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_query_cache',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_raid',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_rtree_keys',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_ssl',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('have_symlink',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('hostname',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('identity',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('init_connect','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('init-file','Yes','Yes',' ',' ','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('init_file',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('init_slave','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_adaptive_hash_index','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_additional_mem_pool_size','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_autoextend_increment','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_buffer_pool_awe_mem_mb','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_buffer_pool_size','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_checksums','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_commit_concurrency','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_concurrency_tickets','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_data_file_path','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_data_home_dir','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_doublewrite','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_fast_shutdown','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_file_io_threads','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_file_per_table','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_flush_log_at_trx_commit','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_flush_method','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_force_recovery','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_lock_wait_timeout','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_locks_unsafe_for_binlog','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_log_arch_dir','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_log_archive','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_log_buffer_size','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_log_file_size','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_log_files_in_group','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_log_group_home_dir','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_max_dirty_pages_pct','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_max_purge_lag','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_mirrored_log_groups','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_open_files','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_rollback_on_timeout','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_support_xa','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_sync_spin_loops','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_table_locks','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_thread_concurrency','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_thread_sleep_delay','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('innodb_use_legacy_cardinality_algorithm','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('insert_id',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('interactive_timeout','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('join_buffer_size','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('keep_files_on_create','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('key_buffer_size','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('key_cache_age_threshold','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('key_cache_block_size','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('key_cache_division_limit','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('language','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('large_files_support',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('large_page_size',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('large-pages','Yes','Yes',' ',' ','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('large_pages',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('last_insert_id',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('lc_time_names',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('license',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('local_infile',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('locked_in_memory',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log_bin',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log-bin','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log-bin-trust-function-creators','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log_bin_trust_function_creators',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log-bin-trust-routine-creators','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log_bin_trust_routine_creators',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log-error','Yes','Yes',' ',' ','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log_error',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log-queries-not-using-indexes','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log_queries_not_using_indexes',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log-slave-updates','Yes','Yes',' ',' ','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log_slave_updates','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log-slow-queries','Yes','Yes',' ',' ','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log_slow_queries',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log-warnings','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('log_warnings',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('long_query_time','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('low-priority-updates','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('low_priority_updates',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('lower_case_file_system',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('lower_case_table_names','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_allowed_packet','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_binlog_cache_size','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_binlog_size','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_connect_errors','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_connections','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_delayed_threads','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_error_count','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_heap_table_size','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_insert_delayed_threads',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_join_size','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_length_for_sort_data','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_prepared_stmt_count','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_relay_log_size','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_seeks_for_key','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_sort_length','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_sp_recursion_depth','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_tmp_tables',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_user_connections','Yes','Yes','Yes','Varies','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('max_write_lock_count','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('multi_range_count','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('myisam_data_pointer_size','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('myisam_max_extra_sort_file_size','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('myisam_max_sort_file_size','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('myisam_mmap_size','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('myisam_recover_options',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('myisam_repair_threads','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('myisam_sort_buffer_size','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('myisam_stats_method','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('named_pipe',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_autoincrement_prefetch_sz','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_cache_check_time','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_force_send','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_index_stat_cache_entries','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_index_stat_enable','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_index_stat_update_freq','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_optimized_node_selection','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_use_exact_count',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ndb_use_transactions','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('net_buffer_length','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('net_read_timeout','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('net_retry_count','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('net_write_timeout','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('new','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('old_passwords',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('open-files-limit','Yes','Yes',' ',' ','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('open_files_limit',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('optimizer_prune_level','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('optimizer_search_depth','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('pid-file','Yes','Yes',' ',' ','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('pid_file',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('plugin_dir','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('port','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('preload_buffer_size','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('prepared_stmt_count',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('profiling',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('profiling_history_size','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('protocol_version',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('pseudo_thread_id',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('query_alloc_block_size','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('query_cache_limit','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('query_cache_min_res_unit','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('query_cache_size','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('query_cache_type','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('query_cache_wlock_invalidate','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('query_prealloc_size','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('rand_seed1',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('rand_seed2',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('range_alloc_block_size','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('read_buffer_size','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('read_only','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('read_rnd_buffer_size','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('relay-log','Yes','Yes',' ',' ','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('relay_log',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('relay-log-index','Yes','Yes',' ',' ','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('relay_log_index','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('relay_log_info_file','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('relay_log_purge','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('relay_log_space_limit','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('rpl_recovery_rank',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('secure-auth','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('secure_auth',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('secure-file-priv','Yes','Yes',' ',' ','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('secure_file_priv',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('server-id','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('server_id',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('shared_memory','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('shared_memory_base_name','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('skip_external_locking','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('skip-networking','Yes','Yes',' ',' ','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('skip_networking',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('skip-show-database','Yes','Yes',' ',' ','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('skip_show_database',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('skip-sync-bdb-logs','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('slave_compressed_protocol','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('slave-load-tmpdir','Yes','Yes',' ',' ','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('slave_load_tmpdir',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('slave-net-timeout','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('slave_net_timeout',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('slave-skip-errors','Yes','Yes',' ',' ','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('slave_skip_errors',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('slave_transaction_retries','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('slow_launch_time','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('socket','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sort_buffer_size','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sql_auto_is_null',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sql_big_selects',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sql_big_tables',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sql_buffer_result',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sql_log_bin',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sql_log_off',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sql_log_update',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sql_low_priority_updates',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sql_max_join_size',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sql-mode','Yes','Yes',' ',' ','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sql_mode',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sql_notes',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sql_quote_show_create',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sql_safe_updates',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sql_select_limit',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sql_slave_skip_counter',' ',' ','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sql_warnings',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ssl-ca','Yes','Yes',' ',' ','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ssl_ca',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ssl-capath','Yes','Yes',' ',' ','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ssl_capath',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ssl-cert','Yes','Yes',' ',' ','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ssl_cert',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ssl-cipher','Yes','Yes',' ',' ','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ssl_cipher',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ssl-key','Yes','Yes',' ',' ','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('ssl_key',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('storage_engine',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sync-bdb-logs','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sync_binlog','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('sync_frm','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('system_time_zone',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('table_cache','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('table_lock_wait_timeout','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('table_type',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('thread_cache_size','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('thread_concurrency','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('thread_stack','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('time_format',' ',' ','Yes','Both','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('time_zone',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('timed_mutexes','Yes','Yes','Yes','Global','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('timestamp',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('tmp_table_size','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('tmpdir','Yes','Yes','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('transaction_alloc_block_size','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('transaction_prealloc_size','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('tx_isolation',' ',' ','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('unique_checks',' ',' ','Yes','Session','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('updatable_views_with_limit','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('version',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('version_comment',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('version_compile_machine',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('version_compile_os',' ',' ','Yes','Global','No');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('wait_timeout','Yes','Yes','Yes','Both','Yes');
INSERT INTO sysvar50 (system_variable_name,cmd_line,option_file,system_var,var_scope,dynamic) VALUES ('warning_count',' ',' ','Yes','Session','No');
